#!/usr/bin/env python3
"""Embed prototypes/models/**/*.glb into prototypes/models.js as data URIs.

The 3D renderer opens straight from disk, where fetch() cannot read sibling files, so
the models travel inside a script instead. Keys are the file name without extension."""
import base64, json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent / "prototypes"
out = {}
for f in sorted((root / "models").rglob("*.glb")):
    out[f.stem] = "data:model/gltf-binary;base64," + base64.b64encode(f.read_bytes()).decode()
(root / "models.js").write_text("// generated by tools/pack-models.py, do not edit\nwindow.MODEL_SRC = " + json.dumps(out) + ";\n")
print(f"packed {len(out)} models into prototypes/models.js ({(root / 'models.js').stat().st_size // 1024} KB)")
